services:
  api:
    build:
      context: .
    expose:
      - 5000
    command: ["fastapi", "run", "--port", "5000"]
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - api_volume:/app/staticfiles
    depends_on:
      - db
      - redis
  db:
    image: postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  api_volume:
  postgres_data:
